---@class Time : Object
---@field public time Single
---@field public timeSinceLevelLoad Single
---@field public deltaTime Single
---@field public fixedTime Single
---@field public unscaledTime Single
---@field public fixedUnscaledTime Single
---@field public unscaledDeltaTime Single
---@field public fixedUnscaledDeltaTime Single
---@field public fixedDeltaTime Single
---@field public maximumDeltaTime Single
---@field public smoothDeltaTime Single
---@field public maximumParticleDeltaTime Single
---@field public timeScale Single
---@field public frameCount Int32
---@field public renderedFrameCount Int32
---@field public realtimeSinceStartup Single
---@field public captureDeltaTime Single
---@field public captureFramerate Int32
---@field public inFixedTimeStep bool
local Time={ }
UnityEngine.Time = Time