---@class TweenPropType : Enum
---@field public value__ Int32
---@field public None number
---@field public X number
---@field public Y number
---@field public Z number
---@field public XY number
---@field public Position number
---@field public Width number
---@field public Height number
---@field public Size number
---@field public ScaleX number
---@field public ScaleY number
---@field public Scale number
---@field public Rotation number
---@field public RotationX number
---@field public RotationY number
---@field public Alpha number
---@field public Progress number
local TweenPropType={ }
FairyGUI.TweenPropType = TweenPropType