---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by test.
--- DateTime: 2020/8/19 11:25
---
---
BingoType = {}

--boss 1.安康鱼2.鳄鱼3.章鱼4.螃蟹 5.雷龙 6.火龙
BingoType.AnKangYuBoss = 1
BingoType.EYuBoss = 2
BingoType.ZhangYuBoss = 3
BingoType.PangXieBoss = 4
BingoType.LongBoss = 5
BingoType.FireDragonBoss = 6

--特殊鱼种 螃蟹(特殊炮)
BingoType.SerialBoomPangXie = 11
BingoType.ZuanTouPangXie = 12
BingoType.HammerPangXie = 13
BingoType.JiGuangPangXie = 14

BingoType.WhirlwindFish = 21

