---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by test.
--- DateTime: 2020/8/19 11:25
---
---加载类型
LoadType = {}

LoadType.Preloading = "Preloading"
LoadType.SceneCommon = "SceneCommon"


