---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-06 15:33
---

--[[
    lua 实现 class
]]

local type = type
local pairs = pairs
local setmetatable = setmetatable

function class(classname, super)
    local superType = type(super)
    local cls

    if superType ~= "function" and superType ~= "table" then
        superType = nil
        super = nil
    end

    if superType == "function" or (super and super.__ctype == 1) then
        -- inherited from native C++ Object
        cls = {}

        if superType == "table" then
            -- copy fields from super
            for k,v in pairs(super) do cls[k] = v end
            cls.__create = super.__create
            cls.super    = super
        else
            cls.__create = super
            cls.ctor = function() end
        end

        cls.__cname = classname
        cls.__ctype = 1

        function cls.new(...)
            local instance = cls.__create(...)
            -- copy fields from class to native object
            for k,v in pairs(cls) do instance[k] = v end
            instance.class = cls
            instance:ctor(...)
            return instance
        end

    else
        -- inherited from Lua Object
        if super then
            cls = {}
            setmetatable(cls, {__index = super})
            cls.super = super
        else
            cls = {ctor = function() end}
        end

        cls.__cname = classname
        cls.__ctype = 2 -- lua
        cls.__index = cls

        function cls.new(...)
            local instance = setmetatable({}, cls)
            instance.class = cls
            instance:ctor(...)
            return instance
        end



    end
    
    cls.instance = setmetatable({}, {
        __index = function(_, k)
            cls.__instance = cls.__instance and cls.__instance or cls.new()
            return cls.__instance[k]
        end,

        __newindex = function(_, k, v)
            cls.__instance = cls.__instance and cls.__instance or cls.new()
            cls.__instance[k] = v
        end,

        __call = function(_,...)
            cls.__instance = cls.__instance and cls.__instance or cls.new(...)
            return cls.__instance
        end
    })
    
    cls.New = cls.new
    return cls
end