---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-07 14:16
---

---@class ENV
-- 静态配置
ENV = {
    IN_EDITOR = Arthas.Tools.InEditor(),
    PLATFORM = Arthas.Tools.GetPlatform(),
    BASE_PREFIX = Arthas.Tools.GetPrefix(),

    --是否绘制碰撞框
    DrawCollisionRect = false
}

