---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-14 15:22
---

GameConst = {}
GameConst.handshake_ok = 200 --握手成功
GameConst.handshake_illegal = 301 --非法账户
GameConst.handshake_new = 404 --新建用户
GameConst.playercreate_ok = 0 --用户创建成功
GameConst.playercreater_ename = 1 --用户名称已经使用过
GameConst.fight_get_in_in_room = 2 --已在房间中进入失败
GameConst.fight_get_in_fail = 1 --进入失败
GameConst.fight_get_in_ok = 0 --进入成功
GameConst.fight_get_in_cost_max = 4--当天消耗金币太多
GameConst.fishmaxlayer = 40--鱼的最大层数
GameConst.fish_type_size_group = 0--鱼群
GameConst.fish_type_size_small = 1--小鱼
GameConst.fish_type_size_middle = 2--中型鱼
GameConst.fish_type_size_big = 3--大鱼
GameConst.fish_type_size_boss = 4--boss
GameConst.fish_group_type_left_to_right = 0--鱼群左到右
GameConst.fish_group_type_path = 1--路径鱼群
GameConst.fish_fit_rnd_nil = 0
GameConst.fish_fit_rnd_once = 1
GameConst.fish_fit_rnd_cfg = 2
GameConst.fish_fit_rnd_cfg_once = 3
GameConst.fish_fit_rnd_everyone = 4
GameConst.fish_play_type_nil = 0
GameConst.fish_play_type_local_bomb = 1
GameConst.fish_play_type_screen_bomb = 2
GameConst.fish_play_type_dasanyuan = 3
GameConst.fish_play_type_fish_type_bomb = 4
GameConst.fish_play_type_energy = 5
GameConst.fish_play_type_dasixi = 6
GameConst.fish_play_type_yiwangdajin = 7
GameConst.fixed_update_time = (1 / 50)
GameConst.area_play_type_max_num = 15
GameConst.draw_collision_rect = false
GameConst.currency_coin = 1
GameConst.currency_fish_coin = 2
GameConst.currency_exp = 3
GameConst.currency_diamond = 4
GameConst.currency_rmb = 5
GameConst.currency_goods = 6
GameConst.currency_contest_score = 201
GameConst.currency_exchange = 60
GameConst.currency_bind_coin = 10
GameConst.server_mode = 0 --服务器模式 0:local 1:stage 2:prod
GameConst.main_edit_menu_show = false--主界面编辑菜单是否显示
GameConst.fix_left_down_pos = true--固定左下角位置
GameConst.show_fish_swim_path_id = true--显示鱼游动的路径id
GameConst.fish_path_mirror_nil = 1
GameConst.fish_path_mirror_x = 2
GameConst.fish_path_mirror_y = 3
GameConst.fish_path_mirror_xy = 4

GameConst.lock_effect_layer_index = 0
GameConst.boom_effect_layer_index = 1
GameConst.bullet_layer_index = 2
GameConst.award_effect_layer_index = 3
GameConst.catch_show_layer_index = 4
GameConst.boom_mask_layer_index = GameConst.fishmaxlayer * 2 - 2
GameConst.use_res_release_skill = 5 --使用资源释放技能
GameConst.sign_in_getted = 0 --已经领取
GameConst.sign_in_getting = 2 --可领取
GameConst.sign_in_not_reach = 3 --未到领取时间
GameConst.fish_catch_type_normal = 0
GameConst.fish_catch_type_extra_drop = 1
GameConst.fish_catch_type_boss = 2
GameConst.fish_catch_type_black_hole = 3
GameConst.fish_catch_type_award_pool = 4
GameConst.fish_type_boss = 2                -- boss 类型
GameConst.fish_type_no_rate = 4                -- 图鉴里不显示倍数
GameConst.online_award_status_getted = 1 --已经领取
GameConst.online_award_status_start = 2 --开始计时领取
GameConst.online_award_status_not_start = 3 --未开始计时领取
GameConst.quit_state_left_confirm_right_cancel = 0
GameConst.quit_state_left_cancel_right_confirm = 1
GameConst.quit_state_mid_confirm = 2
GameConst.quit_state_left_cancel_right_confirm_rank = 4
GameConst.quit_state_mid_confirm_subscibe = 5

GameConst.shop_tab_diamond = "tab_diamond"
GameConst.shop_tab_coin = "tab_coin"
GameConst.shop_tab_skin = "tab_skin"
GameConst.shop_tab_package = "tab_package"
GameConst.shop_tab_mini = "tab_mini"
GameConst.shop_tab_mini_coin = "tab_mini_coin"

GameConst.sceneId_1 = 1  --深海巨鲸渔场id


GameConst.reconnect_type_other_device_login = 1--账号在其他设备登录
GameConst.reconnect_type_kick = 2 --玩家被踢出
GameConst.reconnect_type_socket_error = 3 --网络出错
GameConst.reconnect_type_server_error = 4--服务器异常
GameConst.reconnect_type_user_check_error = 5 --用户校验失败
GameConst.reconnect_type_network_error = 6 --网络状态提示
GameConst.reconnect_admin_kick = 7 --管理员主动踢下线&封号
--小红点类型
GameConst.point_new_task_finish = 1 --新手任务完成
GameConst.point_online_reward = 2 --在线奖励
GameConst.point_weapon = 4 --新武器
GameConst.point_sign = 8 --签到小红点
GameConst.point_first_charge = 16 --首充小红点
GameConst.point_vip_buy = 32 --VIP小红点
GameConst.point_month_card = 64 --月卡小红点
GameConst.point_gift = 128 --赠送小红点
GameConst.point_rank = 8192 --赠送小红点


GameConst.ani_type_frame = 0 --帧动画
GameConst.ani_type_skeleton = 1 --骨骼动画
GameConst.ani_type_3d = 2 --3d动画

--发射子弹失败时发生的动作
GameConst.shoot_bullet_fail_action_sub_allow = 1 --领取低保
GameConst.shoot_bullet_fail_action_open_shop = 2 --

--默认声音大小
GameConst.default_sound = 0.5
GameConst.default_bgm_music = 0.5

GameConst.in_fight_normal = 0 --正常状态，快速进入
GameConst.in_fight_by = 1--捕鱼房间中





GameConst.Dec_Active = 21 --12月活动id
GameConst.server_local = true

GameConst.edition_department_version = true

GameConst.design_width = 1920
GameConst.design_height = 1080
GameConst.design_width_2d = 1280
GameConst.design_height_2d = 720
GameConst.autoFire = 0 --自动发炮
GameConst.noAutoFire = 1--不自动发炮
GameConst.PauseAutoFire = 2--打开界面自动法袍

GameConst.loadMainState = 0 --加载主界面的状态
GameConst.loadFishState = 1 --加载战斗界面的状态
GameConst.FISH_PAGE = "fish_page"
GameConst.MAIN_PAGE = "main_page"


GameConst.activity_bomb = 'bomb'
GameConst.activity_bonus = 'bonus'
GameConst.activity_worldcup = 'worldcup2'--新的世界杯活动，老得不用了
GameConst.activity_common = 'multi_at'--公共活动
GameConst.activity_rank = 'top_double'--排行榜双倍奖励
GameConst.activity_red_pack = 'red_pack'--喇叭活动

GameConst.activity_common_shop = 1--商场返利（充值）
GameConst.activity_common_rew = 2--渔场内抽奖页面
GameConst.activity_common_daymatch = 3--活动日常赛
GameConst.activity_common_register = 4--签到奖励
GameConst.activity_common_share = 5--分享奖励 每日转盘
GameConst.activity_common_since = 6--第四关奖金池
GameConst.activity_common_directchanges = 101--直接兑换
GameConst.activity_common_giftbox = 102--分享礼盒
GameConst.activity_common_rankactivity = 103--排行榜活动
GameConst.activity_common_red_task = 104--红包
GameConst.activity_common_main_rank = 105--主界面排行榜

GameConst.activity_currency_one = 81 --12月活动币1的goodsID
GameConst.activity_currency_two = 82  --  币2
GameConst.activity_currency_three = 83  --  币3

GameConst.coin_type_exchange = "exchange_card"
GameConst.coin_type_activity = "at_coin"
GameConst.coin_type_worldcup = "worldcup"
GameConst.coin_type_wheel = "zbwk_coin"--转盘活动

GameConst.scene_resource_coin = 1
GameConst.scene_resource_contest_coin = 2

GameConst.contest_daily_scene_id = 5
GameConst.contest_tz_scene_id = 6
GameConst.contest_match_scene_id = 7
GameConst.contest_qd_scene_id = 8

GameConst.platform = GameConst.platform_h5
GameConst.platform_h5 = "h5"
GameConst.platform_wx_sg = "wx_gs"


GameConst.public_no_id_nil = 0 --无渠道
GameConst.public_no_id_jjh = 1--集结号娱乐公众号
GameConst.public_no_id_jjhh5 = 2--集结号捕鱼H5公众号
GameConst.public_no_id_ljby = 3 --游戏坛子

GameConst.month_card_id = 18

GameConst.week_card_id = 41
GameConst.worldcup_battery_id = 9

GameConst.show_banner = 0x08--鱼场是否俯视视角
GameConst.show_red = 0x10--渔场是否显示红包


GameConst.start_scene_pull = 1104 --从微信聊天界面下拉菜单启动游戏
GameConst.start_scene_collect = 1103 --从发现我的小程序进入

GameConst.user_status_normal = "normal"
GameConst.user_status_ban = "ban"
GameConst.user_status_limited = "limited"


GameConst.novice_guide_click = "click"
GameConst.novice_guide_classicInto = "classicInto"
GameConst.novice_guide_fight = "fight"
GameConst.novice_guide_shoot = "shoot"
GameConst.novice_guide_slider = "slider"
GameConst.novice_guide_new = "new"
GameConst.novice_guide_acceptNew = "acceptNew"
GameConst.novice_guide_quitNew = "quitNew"
GameConst.novice_guide_daily = "daily"
GameConst.novice_guide_daily_go = "dailyGo"
GameConst.novice_guide_daily_use_prop = "dailyUseProp"
GameConst.novice_guide_daily_accept = "acceptDaily"

GameConst.novice_guide_quitDaily = "quitDaily"
GameConst.novice_guide_unlockBattery = "unlockBattery"
GameConst.novice_guide_changeBattery = "changeBattery"


GameConst.platform_yyly = "yyly"
GameConst.platform_360 = "360h5"
GameConst.platform_yawy = "yawy"
GameConst.platform_aiqiyi = "aiqiyi"
GameConst.platform_cocos = "cocos"

GameConst.platform_android_baidu = "baidu"
GameConst.platform_android_huawei = "huawei"
GameConst.platform_android_360 = "360"
GameConst.platform_android_app = "app"
GameConst.platform_android_meizu = "meizu"
GameConst.platform_android_yyb = "yyb"
GameConst.platform_android_aiqiyi = "aiqiyi"
GameConst.platform_android_xiaomi = "xiaomi"
GameConst.platform_android_ali = "ali"
GameConst.platform_android_quick = "quick"


GameConst.novice_guide_slider_contest = "slider_to_contest"
GameConst.novice_guide_open_contest_icon = "open_contest_icon"
GameConst.novice_guide_sign_contest = "sign_contest"
GameConst.novice_guide_sign_contest_confirm = "sign_contest_confirm"
GameConst.novice_guide_rank = "rank"
GameConst.novice_guide_quitRank = "rankQuit"
GameConst.novice_guide_quitFight = "quitFight"
GameConst.novice_guide_open_follow = "openFollow"

GameConst.font_red = "red"
GameConst.font_red_sheet = "取出立即购买获得消确定继 续搜索同意拒绝复制升级解 锁游戏领前往充放置全部加 入房间重抽报名免费"
GameConst.font_green = "green"
GameConst.font_green_sheet = "存入取消查看确定装备邀请 一键升级返回大厅反馈分享 礼包码炫耀下领奖励提交开 启使用完成布置规则询赠送 购买个观看广告订阅"
GameConst.wxSDKVersion = "2.0.6"


GameConst.fight_mode_2d = 0
GameConst.fight_mode_3d = 1


GameConst.fish_action_swim = "swim"
GameConst.fish_action_hit = "hit"
GameConst.fish_action_death = "death"
GameConst.fish_action_special = "spec"

GameConst.PackageType = {
    UI                  = "UI",
}

GameConst.from_login = "login"
GameConst.from_shop = "shop"
GameConst.from_main = "main"
GameConst.from_month = "month"
GameConst.from_gift = "Gift"
GameConst.from_bank = "bank"




--场景玩法类型
GameConst.scene_play_extra_drop = 1--额外掉落
GameConst.scene_play_money_bag = 2--钱袋捕获
GameConst.scene_play_black_hole = 3--黑洞
GameConst.scene_play_award_pool = 4--奖池

--鱼游动方向
GameConst.fish_from_left = 1 --从左往右
GameConst.fish_from_right = -1 --从右往左

--场景大小boss stage
GameConst.fishGroup_stage = 1
GameConst.boss_stage_small = 2 --小boss阶段
GameConst.boss_stage_big = 3 --大boss阶段



