---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-11 10:11
---
-- LOAD
require 'Base.Class'
require 'typeof'
require 'Base.Table'
require 'Base.Functions'

--------------------------------------------------
local ArthasJSON = require 'cjson'
decode = ArthasJSON.decode
encode = ArthasJSON.encode
cjson_null = ArthasJSON.null
bit = require("bit")
--------------------------------------------------


--------
require "Base.ENV"
require "Util.Log"
require 'Base.GameConst'
require 'Base.GameEvent'
require "Base.Resource"
require 'Fight.Tool.FightEvent'
require 'Base.GameConstSkill'
require 'Util.GameTimer'
require "Util.TimeTools"
require "Util.MathTools"
require "Util.GameTip"
require "Util.GameTools"
require "Util.SwitchOffTool"
require "Util.GamePool"
require "Util.MeshSharing"

require "proto_proto"

require "Util.GameConfirmInfo"
require "Struct.QuitTipInfo"
require "Struct.CertificationInfo"
require "Enum.BingoType"
require "Enum.LoadType"

require 'UI.Assist.UIEffectType'
require 'UI.Assist.UIType'
require 'UI.Assist.UIBase'
require "UI.Assist.UIDialogBase"
require 'UI.Assist.FairyGUI'
require 'UI.Button'
require 'Data.manifest'

require "Manager.GameEventDispatch"
require "Manager.UIManager"
require "Manager.WebSocketManager"
require 'Manager.ApiManager'
require 'Manager.UIEffectManager'
require 'Manager.UIManager'
require 'Manager.SpineManager'
require 'Manager.AnimalManger'
require 'Manager.GameInit'
require 'Manager.ListManager'
require 'Manager.SoundManager'
require "Manager.Handler"
require "Manager.UIPackageManager"
require "Manager.ResourceManifest"
require "Base.NetSender"

require 'Model.GunM'
require 'Model.LevelM'
require 'Model.SkillM'
require 'Model.CompenM'
require 'Model.FishTypeM'
require 'Model.ExchangeM'
require 'Model.OnLineM'
require 'Model.LoadTipM'


--auto gen by walk folder
require "Manager.ConfigManager"
require "Engine.Pool.Pool"
require "Engine.Fsm.FSM"
require "Engine.Fsm.State"

require "Proto.C2s_shootBullet"
require "Proto.S2c_fightSync"
require "Proto.ProtoSeatInfo"
require "Proto.ProtoCatchFish"
require "Proto.ProtoCatchAward"
require "Proto.ProtoFishInfo"
require "Proto.ProtoSerialFrying"


--
--
--require "Proto.C2s_34002"
--require "Proto.S2c_profile"
--require "Proto.SharePro"
--require "Proto.S2c_13002"
--require "Proto.C2s_34004"
--require "Proto.ProtoFightPlayerCoint"
--require "Proto.ProtoFightEatCoinRet"
--require "Proto.C2s_12001"
--require "Proto.C2s_shootBullet"
--require "Proto.S2c_fightSync"
--require "Proto.S2c_playercreate"
--require "Proto.S2c_12023"
--require "Proto.C2s_20002"
--require "Proto.S2c_21000"
--require "Proto.ComPro"
--require "Proto.S2c_10008"
--require "Proto.S2c_10009"
--require "Proto.ProtoObject"
--require "Proto.S2c_12030"
--require "Proto.C2s_30002"
--require "Proto.S2c_17002"
--require "Proto.C2s_14000"
--require "Proto.S2c_17003"
--require "Proto.S2c_12033"
--require "Proto.S2c_12027"
--require "Proto.C2s_14031"
--require "Proto.S2c_10007"
--require "Proto.S2c_12029"
--require "Proto.S2c_12015"
--require "Proto.S2c_12028"
--require "Proto.C2s_13003"
--require "Proto.S2c_roomGetIn"
--require "Proto.S2c_22001"
--require "Proto.S2c_handshake"
--require "Proto.S2c_22000"
--require "Proto.C2s_19007"
--require "Proto.S2c_18001"
--require "Proto.S2c_22003"
--require "Proto.C2s_17001"
--require "Proto.ProtoSeatInfo"
--require "Proto.ProtoCatchFish"
--require "Proto.MakePro"
--require "Proto.S2c_14006"
--require "Proto.C2s_19000"
--require "Proto.C2s_15001"
--require "Proto.S2c_20003"
--require "Proto.S2c_20001"
--require "Proto.S2c_22004"
--require "Proto.C2s_19002"
--require "Proto.S2c_16001"
require "Proto.C2s_12120"
require "Proto.C2s_12122"
require "Proto.C2s_12130"
require "Proto.S2c_12131"
require "Proto.S2c_12132"

require "Fight.Game.Game"
require "Fight.Game.GameNetwork"
require "Fight.Game.StateGameInit"
require "Fight.Game.StateGameLogin"
require "Fight.Game.StateGameMain"
require "Fight.Game.StateGameDisconnect"
require "Fight.Game.StateGameNotice"
require "Fight.Game.StateGameFish"
require "Fight.Game.StateGameLoading"
require "Fight.Bullet.BulletInfoParser"

require "Fight.Cmd.CmdGateOut"

require "Fight.Cmd.CmdGateIn"
require "Fight.Cmd.CmdGateOut"

require "Fight.Cmd.CmdHandleSkill"
require "Fight.Cmd.CmdHandleRoom"
require "Fight.Cmd.CmdHandleNetwork"
require "Fight.Cmd.CmdHandleMatch"
require "Fight.Context.FightContext"

require "Fight.Context.ShootContext"
require "Fight.Context.FishContext2D"
require "Fight.Context.BatteryContext"

require "Fight.Bullet.BulletInfoParser"
require "Fight.Bullet.BulletFactory"
require "Fight.Bullet.Bullet"
require "Fight.Bullet.StateBulletMove"
require "Fight.Bullet.StateBulletHit"
require "Fight.Bullet.StateBulletWait"
require "Fight.Bullet.StateBulletFly"
require "Fight.Bullet.StateBulletStop"

require "Fight.Path.PathService"
require "Fight.Path.PathResult"
require "Fight.Path.PathContext"
require "Fight.Path.BezierPath2D"
require "Fight.Path.EyuPath2D"

require "Fight.Fishery.Fishery"
require "Fight.Fishery.FisheryForm"
require "Fight.Fishery.StateFisheryRunning"
require "Fight.Fishery.StateFisheryBoom"
require "Fight.Fishery.StateFisheryExit"
require "Fight.Fishery.FisheryTick"
require "Fight.Fishery.FishLayer"
require "Fight.Fishery.MatchStateWaitJoin"
require "Fight.Fishery.MatchStateWaitPrepare"
require "Fight.Fishery.MatchStateWaitCountDown"
require "Fight.Fishery.MatchStateWaitStart"
require "Fight.Fishery.MatchStateStart"
require "Fight.Fishery.MatchStateExit"

require "Fight.Fish.FishFactory"
require "Fight.Fish.Fish2D"
require "Fight.Fish.CollisionRectangle"
require "Fight.Fish.StateFishDead"
require "Fight.Fish.StateFishRunning"
require "Fight.Fish.StateFishHit"
require "Fight.Fish.StateFishStop"
require "Fight.Fish.StateFishFreeze"

require "Fight.Seat.Seat"
require "Fight.Seat.SeatSkill"
require "Fight.Seat.SeatRouter"
require "Fight.Seat.SeatEffect"

require "Fight.Seat.StateSeatAuto"
require "Fight.Seat.StateSeatNormal"
require "Fight.Seat.StateSeatLock"
require "Fight.Seat.SeatRouter"
require "Fight.Seat.StateSeatBoom"
require "Fight.Seat.SeatViolent"
require "Fight.Seat.StateSeatExit"
require "Fight.Seat.StateSeatRange"
require "Fight.Seat.StateSeatWait"
require "Fight.Seat.StateSeatLockType"

require "Fight.Tool.EaseTools"
require "Fight.Tool.FightConst"
require "Fight.Tool.FightTools"
require "Fight.Tool.FightEvent"
require "Fight.Tool.FightSoundManager"
require "Fight.Tool.CollisionRect"
require "Fight.Tool.Collision"

require "Fight.Mapper.MirrorMapper"
require "Fight.Mapper.MirrorContext"
require "Fight.Mapper.GameScreen"
-- model
require "Model.FightM"
require "Model.RoleInfoM"
require "Model.FishTypeM"
require "Model.LoginInfoM"
require "Model.RegiM"
require "Model.RTipM"
require "Model.LevelM"
require "Model.RewardM"
require "Model.ActivityM"
require "Model.HorseM"
require "Model.CertificationM"
require "Model.LoginM"
require "Model.MatchM"
require "Model.RuleM"
require "Model.MsgM"


-- control
require "Control.RoleInfoC"
require "Control.LoginInfoC"
require "Control.ShopC"
require "Control.RTipC"
require "Control.LevelC"
require "Control.TaskC"
require "Control.FightC"
require "Control.BatteryC"
require "Control.BankC"
require "Control.RedPointC"
require "Control.HorseC"
require "Control.ActivityC"
require "Control.MatchC"
require "Control.RuleC"
require "Control.RewardC"
require "Control.OnLineC"
require "Control.MsgC"
require "Control.RegiC"
require "Control.SerialFryingC"
require "Control.BossAwakeC"

require "Control.EYuAwakeC"
require "Control.AnKangYuAwakeC"
require "Control.HammerAwakeC"
require "Control.ZhangYuAwakeC"
require "Control.ZuantoupaoC"
require "Control.DragonAwakeC"
require "Control.FireDragonAwakeC"


--Context
require("Fight.Context.ShowGetCoinInfo")
require("Fight.Context.ProtoCatchAward")
require("Fight.Context.AgentGetInfo")

--effect
require("Fight.Effect.EffectBase")
require("Fight.Effect.GoodsFlyManager")
require("Fight.Effect.GoodsFlyEffect")
require("Fight.Effect.FishDeadEffect")
require("Fight.Effect.FullScreenCoinEffect")
require("Fight.Effect.FullScreenCoinEffectSingle")
require("Fight.Effect.SpecialPaoEffect")
require("Fight.Effect.ZhangYuAwake")
require("Fight.Effect.EYuAwake")
require("Fight.Effect.AnKangYuAwake")
require("Fight.Effect.HammerAwake")
require("Fight.Effect.NumChgEffect")
require("Fight.Effect.ZuantoupaoEffect")
require("Fight.Effect.FontClipEffect")
require("Fight.Effect.SerialFryingEffect")
require("Fight.Effect.ShadowShake")
require("Fight.Effect.WhirlwindShake")
require("Fight.Effect.XZEffect")
require("Fight.Effect.Bingo.BingoControl")
require("Fight.Effect.Bingo.BingoSingle")
require("Fight.Effect.SpecialEffect")
require("Fight.Effect.EffectManager")
require("Fight.Effect.DragonAwake")
require("Fight.Effect.FireDragonAwake")


--UI
require "UI.UIBankPage"
require "UI.UIMatchPage"
require "UI.UIMonthCardPage"
require "UI.UITaskNewPage"
require "UI.UIResetCommonPage"
require "UI.UIExchangePage"
require "UI.UIFishTypePage"
require "UI.UISettingPage"
require "UI.UIInfoPage"
require "UI.UILoadPage"
require "UI.UIQuitTipPage"
require "UI.UIShopPage"
require "UI.UIHorseTipPage"
require "UI.UIChangeSkinPage"
require "UI.UIRewardPage"
require "UI.UITaskDailyPage"
require "UI.UIRedActivityPage"
require "UI.UIRegisterPage"
require "UI.UIFishPage"
require "UI.RewardBox"
require "UI.UIRewardTipPage"
require "UI.UIPackPage"
require "UI.UIMainPage"
require "UI.UILoginPage"
require "UI.UICertificationPage"
require "UI.UIBrokePage"
require "UI.UITipPage"
require "UI.UIRankPage"

--ui item
require "UI.item.SerialFryingItem"
