FightConst = {}

FightConst._designWidth=1920
FightConst._designHeight=1080
FightConst.fish_stage_3d_0=0
FightConst.fish_stage_3d_1=1
FightConst.fish_stage_3d_2=2
FightConst.fish_stage_3d_3=3
FightConst.fish_catch_type_cornucopia=7
FightConst.fish_catch_type_dfdg=8
FightConst.fish_catch_type_dsy=9
FightConst.fish_catch_type_dsx=10
FightConst.fish_catch_type_torpedo=11
FightConst.fishmaxlayer=40
FightConst.fish_type_size_group=0
FightConst.fish_type_size_small=1
FightConst.fish_type_size_middle=2
FightConst.fish_type_size_big=3
FightConst.fish_type_size_boss=4
FightConst.fish_group_type_left_to_right=0
FightConst.fish_group_type_path=1
FightConst.fish_fit_rnd_nil=0
FightConst.fish_fit_rnd_once=1
FightConst.fish_fit_rnd_cfg=2
FightConst.fish_fit_rnd_cfg_once=3
FightConst.fish_fit_rnd_everyone=4
FightConst.fish_play_type_nil=0
FightConst.fish_play_type_local_bomb=1
FightConst.fish_play_type_screen_bomb=2
FightConst.fish_play_type_dasanyuan=3
FightConst.fish_play_type_fish_type_bomb=4
FightConst.fish_play_type_energy=5
FightConst.fish_play_type_dasixi=6
FightConst.fish_play_type_yiwangdajin=7
FightConst.area_play_type_max_num=15
FightConst.draw_collision_rect=false
FightConst.currency_coin=1
FightConst.currency_fish_coin=2
FightConst.currency_exp=3
FightConst.currency_diamond=4
FightConst.currency_rmb=5
FightConst.currency_goods=6
FightConst.currency_contest_score=201
FightConst.currency_exchange=60
FightConst.currency_bind_coin=10
FightConst.skined_pao_lock = 9       -- 锁定类型的炮
FightConst.skin_type_jiguangpao=100 -- 激光炮皮肤
FightConst.skin_type_zuantoupao=101 -- 钻头炮皮肤
FightConst.goods_type_jiguangpao=110 -- 激光炮
FightConst.goods_type_zuantoupao=111 -- 钻头炮
FightConst.goods_type_torpedo_beg=401
FightConst.goods_type_torpedo_end=410
FightConst.server_mode=0
FightConst.main_edit_menu_show=false
FightConst.fix_left_down_pos=true
FightConst.show_fish_swim_path_id=true
FightConst.fish_path_mirror_nil=1
FightConst.fish_path_mirror_x=2
FightConst.fish_path_mirror_y=3
FightConst.fish_path_mirror_xy=4
FightConst.skill_type_freeze=1
FightConst.skill_type_lock=2
FightConst.skill_type_call=3
FightConst.skill_type_violent=4
FightConst.skill_type_boom=5
FightConst.skill_type_auto=6
FightConst.lock_effect_layer_index=0
FightConst.boom_effect_layer_index=1
FightConst.bullet_layer_index=2
FightConst.award_effect_layer_index=3
FightConst.catch_show_layer_index=4
FightConst.boom_mask_layer_index=40*2-2
FightConst.use_res_release_skill=5
FightConst.sign_in_getted=0
FightConst.sign_in_getting=2
FightConst.sign_in_not_reach=3
FightConst.fish_catch_type_normal=0
FightConst.fish_catch_type_extra_drop=1
FightConst.fish_catch_type_boss=2                                       -- 捕获boss
FightConst.fish_catch_type_black_hole=3
FightConst.fish_catch_type_award_pool=4
FightConst.fish_catch_type_award_change = 12                            -- 捕获类型，奖励改变
FightConst.fish_catch_type_boom = 13                                    -- 捕获类型， 连环炸弹

---100 - 200之间为boss觉醒ctype
FightConst.fish_catch_type_boss_awake = 100
FightConst.fish_catch_type_eyu_awake = 101 -- 捕获类型,鳄鱼觉醒
FightConst.fish_catch_type_ankangyu_awake = 102 -- 捕获类型,鮟鱇鱼觉醒
FightConst.fish_catch_type_leishenchui_awake = 103 -- 捕获类型,雷神锤
FightConst.fish_catch_type_dragon_awake = 104 -- 捕获类型,雷龙
FightConst.fish_catch_type_fireDragon_awake = 105 -- 捕获类型,火龙
FightConst.fish_catch_type_boss_max_awake = 200

FightConst.online_award_status_getted=1
FightConst.online_award_status_start=2
FightConst.online_award_status_not_start=3
FightConst.quit_state_left_confirm_right_cancel=0
FightConst.quit_state_left_cancel_right_confirm=1
FightConst.quit_state_mid_confirm=2
FightConst.quit_state_left_cancel_right_confirm_rank=4
FightConst.quit_state_mid_confirm_subscibe=5
FightConst.shop_tab_diamond="tab_diamond"
FightConst.shop_tab_coin="tab_coin"
FightConst.shop_tab_skin="tab_skin"
FightConst.shop_tab_package="tab_package"
FightConst.shop_tab_mini="tab_mini"
FightConst.shop_tab_mini_coin="tab_mini_coin"
FightConst.sceneId_1=1
FightConst.reconnect_type_other_device_login=1
FightConst.reconnect_type_kick=2
FightConst.reconnect_type_socket_error=3
FightConst.reconnect_type_server_error=4
FightConst.reconnect_type_user_check_error=5
FightConst.reconnect_type_network_error=6
FightConst.reconnect_admin_kick=7
FightConst.point_new_task_finish=1
FightConst.point_online_reward=2
FightConst.point_weapon=4
FightConst.point_sign=8
FightConst.point_first_charge=16
FightConst.point_vip_buy=32
FightConst.point_month_card=64
FightConst.point_gift=128
FightConst.point_rank=8192
FightConst.ani_type_frame=0
FightConst.ani_type_skeleton=1
FightConst.ani_type_3d=2
FightConst.shoot_bullet_fail_action_sub_allow=1
FightConst.shoot_bullet_fail_action_open_shop=2
FightConst.default_sound=0.5
FightConst.default_bgm_music=0.5
FightConst.in_fight_normal=0
FightConst.in_fight_by=1
FightConst.scene_play_extra_drop=1
FightConst.scene_play_money_bag=2
FightConst.scene_play_black_hole=3
FightConst.scene_play_award_pool=4
FightConst.Dec_Active=21
FightConst.server_local=true
FightConst.edition_department_version=true
FightConst.design_width=1920
FightConst.design_height=1080
FightConst.autoFire=0
FightConst.noAutoFire=1
FightConst.PauseAutoFire=2
FightConst.loadMainState=0
FightConst.loadFishState=1
FightConst.FISH_PAGE="fish_page"
FightConst.MAIN_PAGE="main_page"
FightConst.activity_bomb='bomb'
FightConst.activity_bonus='bonus'
FightConst.activity_worldcup='worldcup2'
FightConst.activity_common='multi_at'
FightConst.activity_rank='top_double'
FightConst.activity_common_shop=1
FightConst.activity_common_rew=2
FightConst.activity_common_daymatch=3
FightConst.activity_common_register=4
FightConst.activity_common_share=5
FightConst.activity_common_since=6
FightConst.activity_common_directchanges=101
FightConst.activity_common_giftbox=102
FightConst.activity_common_rankactivity=103
FightConst.activity_common_red_task=104
FightConst.activity_common_main_rank=105
FightConst.activity_currency_one=81
FightConst.activity_currency_two=82
FightConst.activity_currency_three=83
FightConst.coin_type_exchange="exchange_card"
FightConst.coin_type_activity="at_coin"
FightConst.coin_type_worldcup="worldcup"
FightConst.coin_type_wheel="zbwk_coin"
FightConst.scene_resource_coin=1
FightConst.scene_resource_contest_coin=2
FightConst.contest_daily_scene_id=5
FightConst.contest_tz_scene_id=6
FightConst.contest_match_scene_id=7
FightConst.contest_qd_scene_id=8
FightConst.platform="h5"
FightConst.platform_h5="h5"
FightConst.platform_wx_sg="wx_gs"
FightConst.public_no_id_nil=0
FightConst.public_no_id_jjh=1
FightConst.public_no_id_jjhh5=2
FightConst.public_no_id_ljby=3
FightConst.month_card_id=18
FightConst.week_card_id=41
FightConst.worldcup_battery_id=9
FightConst.show_banner=0x08
FightConst.show_red=0x10
FightConst.start_scene_pull=1104
FightConst.start_scene_collect=1103
FightConst.user_status_normal="normal"
FightConst.user_status_ban="ban"
FightConst.user_status_limited="limited"
FightConst.novice_guide_click="click"
FightConst.novice_guide_classicInto="classicInto"
FightConst.novice_guide_fight="fight"
FightConst.novice_guide_shoot="shoot"
FightConst.novice_guide_slider="slider"
FightConst.novice_guide_new="new"
FightConst.novice_guide_acceptNew="acceptNew"
FightConst.novice_guide_quitNew="quitNew"
FightConst.novice_guide_daily="daily"
FightConst.novice_guide_daily_go="dailyGo"
FightConst.novice_guide_daily_use_prop="dailyUseProp"
FightConst.novice_guide_daily_accept="acceptDaily"
FightConst.novice_guide_quitDaily="quitDaily"
FightConst.novice_guide_unlockBattery="unlockBattery"
FightConst.novice_guide_changeBattery="changeBattery"
FightConst.platform_yyly="yyly"
FightConst.platform_360="360h5"
FightConst.platform_yawy="yawy"
FightConst.platform_aiqiyi="aiqiyi"
FightConst.platform_cocos="cocos"
FightConst.platform_android_baidu="baidu"
FightConst.platform_android_huawei="huawei"
FightConst.platform_android_360="360"
FightConst.platform_android_app="app"
FightConst.platform_android_meizu="meizu"
FightConst.platform_android_yyb="yyb"
FightConst.platform_android_aiqiyi="aiqiyi"
FightConst.platform_android_xiaomi="xiaomi"
FightConst.platform_android_ali="ali"
FightConst.platform_android_quick="quick"
FightConst.novice_guide_slider_contest="slider_to_contest"
FightConst.novice_guide_open_contest_icon="open_contest_icon"
FightConst.novice_guide_sign_contest="sign_contest"
FightConst.novice_guide_sign_contest_confirm="sign_contest_confirm"
FightConst.novice_guide_rank="rank"
FightConst.novice_guide_quitRank="rankQuit"
FightConst.novice_guide_quitFight="quitFight"
FightConst.novice_guide_open_follow="openFollow"
FightConst.font_red="red"
FightConst.font_red_sheet="取出立即购买获得消确定继 续搜索同意拒绝复制升级解 锁游戏领前往充放置全部加 入房间重抽报名免费"
FightConst.font_green="green"
FightConst.font_green_sheet="存入取消查看确定装备邀请 一键升级返回大厅反馈分享 礼包码炫耀下领奖励提交开 启使用完成布置规则询赠送 购买个观看广告订阅"
FightConst.wxSDKVersion="2.0.6"
FightConst.fight_mode_2d=0
FightConst.fight_mode_3d=1
FightConst.fish_action_swim="swim"
FightConst.fish_action_hit="hit"
FightConst.fish_action_death="death"
FightConst.fish_action_special="spec"
FightConst.fish_special_type_nil=0
FightConst.fish_special_type_dfdg=10
FightConst.fish_special_type_dsy_beg=20
FightConst.fish_special_type_dsy_boss=20
FightConst.fish_special_type_dsy_less=21
FightConst.fish_special_type_dsy_end=29
FightConst.fish_special_type_dsx_beg=30
FightConst.fish_special_type_dsx_boss=30
FightConst.fish_special_type_dsx_less=31
FightConst.fish_special_type_dsx_end=39
FightConst.lock_mode_auto_shoot=1
FightConst.lock_mode_not_auto_shoot=2
FightConst.auto_mode_conditional=1
FightConst.auto_mode_unconditional=2
-- 鱼死亡效果枚举值,具体见: http://183.131.147.91:8890/web/#/33?page_id=688
FightConst.fish_death_type_none = 0; -- 默认击杀
FightConst.fish_death_type_laser_cannon = 1; -- 激光炮击杀
FightConst.fish_death_type_drill_cannon = 2; -- 钻头炮击杀
FightConst.fish_death_type_whirlwind_cannon = 3; -- 旋风鱼击杀
FightConst.fish_death_type_boom_fish_boom = 100; -- 炸弹鱼爆炸击杀鱼
FightConst.fish_death_type_drill_cannon_boom = 101; -- 钻头炮爆炸击杀鱼
FightConst.fish_death_type_boss_awake = 200 --boss觉醒
FightConst.fish_death_type_eyu_awake = 201 -- 鳄鱼觉醒
FightConst.fish_death_type_anakangyu_awake = 202 -- 鮟鱇鱼觉醒
FightConst.fish_death_type_leishenchui_awake = 203 -- 雷神锤
FightConst.fish_death_type_dragon_awake = 204 -- 雷龙
FightConst.fish_death_type_fireDragon_awake = 205 -- 火龙
FightConst.fixed_update_time = 1/50;    --帧率

--鱼死亡动画播放
FightConst.playCoin = 1 --播放金币动画
FightConst.playNumAndCoin = 2 --播放金币&数字动画

--奖励鱼类型
FightConst.fish_award_whirlwind = 1;    --旋风鱼的奖励

--旋风鱼的锁定鱼组类型
FightConst.fish_group_lock_whirlwind = 3;
