---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-08 10:00
---

---@class AnimalManger
AnimalManger = class("AnimalManger")

local AssetBundle = UnityEngine.AssetBundle
AnimalManger.LoadAni = {}

function AnimalManger:ctor()
    ---@type GMovieClip
    self.ani = nil
    self.width = nil
    self.height = nil
    self.getCache = nil
end

---@return AnimalManger @用户创建在编辑器中拖放的帧动画
function AnimalManger.createByAni(ani)
    local _ani = AnimalManger.New()
    _ani.ani = ani
    _ani.width = ani.width
    _ani.height = ani.height
    return _ani
end

---@return AnimalManger
function AnimalManger.create(url, packageName, resName, cache)
    UIPackageManager.instance:AddPackage(url, packageName)

    local _ani = AnimalManger.New()
    local getCache = cache or false
    local ani = nil
    if getCache then
        ani = Game.instance.aniPool:GetObject("ui://"..packageName.."/"..resName)
    else
      ani = UIPackage.CreateObject(packageName,resName)
    end
    if not ani then
        Log.debug("AnimalManger: ani not found", "packageName", packageName, "resName", resName)
        return nil
    end

    ani.pivotAsAnchor = true
    _ani.ani = ani
    _ani.width = ani.width
    _ani.height = ani.height
    _ani.getCache = getCache

    return _ani
end

---@param intervel number @设置帧间隔
function AnimalManger:setSpeed(intervel)
    --self.ani.timeScale = (1000 / intervel) / 30 * (60 / 30)
    return self
end

function AnimalManger:setPivot(pivotX, pivotY)
    self.ani.pivotX = pivotX
    self.ani.pivotY = pivotY
    return self
end

function AnimalManger:setScale(scaleX, scaleY)
    self.ani.scaleX = scaleX
    self.ani.scaleY = scaleY
end

---@param parent GComponent
function AnimalManger:addTo(parent)
    parent:AddChild(self.ani)
end

function AnimalManger:play(isLoop)
    if isLoop then
        self.ani:SetPlaySettings(0, -1, 0, -1)
    else
        self.ani:SetPlaySettings(0, -1, 1, -1)
    end
end

function AnimalManger:pause()
    self.ani.playing = false
end

---@param x number skewX
---@param y number skewY
function AnimalManger:setSkew(x, y)
    self.ani.displayObject.skew = Vector2.New(x, y)
end

---@param layerNum number layer层的值 例如 ui层是5
function AnimalManger:setLayer(layerNum)
    self.ani.displayObject.layer = layerNum
end

function AnimalManger:resume()
    self.ani.playing = true
end

function AnimalManger:destroy()
    self.ani:RemoveFromParent()
    if self.getCache then
        Game.instance.aniPool:ReturnObject(self.ani)
    else
        self.ani:Dispose()
    end
end

function AnimalManger:setVisible(visible)
    self.ani.visible = visible
end