GameInit = class("GameInit")

function GameInit:ctor()
    self.ModelInit()
    self.ControlInit()
end

function GameInit:ModelInit()
    RoleInfoM.instance()
    LoginInfoM.instance()
    RegiM.instance()
    --MsgM.instance()
    --FishTypeM.instance()
    RewardM.instance()
    LevelM.instance()
    RTipM.instance()
    HorseM.instance()
    RuleM.instance()
    OnLineM.instance()
    --UpgradeM.instance()
    --RuleM.instance()
    --CompenM.instance()
    --LoginM.instance()
    LoadTipM.instance()
    --MatchM.instance()
    ActivityM.instance()
    --SubscriptionM.instance()
    --AdM.instance()
end

function GameInit:ControlInit()
    RoleInfoC.instance()
    LoginInfoC.instance()
    ShopC.instance()
    --HeartbeatC.instance()
    FightC.instance()
    MatchC.instance()
    MsgC.instance()
    --FishTypeC.instance()
    --RewardC.instance()
    TaskC.instance()
    LevelC.instance()
    RTipC.instance()
    BatteryC.instance()
    HorseC.instance()
    --
    OnLineC.instance()
    RedPointC.instance()
    --UpgradeC.instance()
    RuleC.instance()
    RegiC.instance()
    --CompenC.instance()
    --LoginC.instance()
    ActivityC.instance()
    BankC.instance()
    RewardC.instance()
    --MatchC.instance()

    --SubscriptionC.instance()
    --AdC.instance()

end
