---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by abner.
--- DateTime: 2020-05-07 13:58
---

---@class ListManager
ListManager = class("ListManager")

function ListManager:ctor()
    self.list = null
    self.length = 0
    self.func = null
    self.classSelf = null
    self.data = null
end

function ListManager.creat(listObj, data, func, classSelf)
    local oneList = ListManager.New();
    oneList.list = listObj
    oneList.func = func
    oneList.classSelf = classSelf
    oneList.length = #data
    oneList.data = data
    --oneList.list.numItems = oneList.length
    oneList.list:RemoveChildrenToPool()
    if func ~= nil then
        for i = 1, oneList.length do
            local cell = oneList.list:AddItemFromPool()
            --func(self,index start 0,box,info)
            oneList.func(classSelf, (i - 1), cell, data[i])
        end
    end
    return oneList
end

function ListManager:update(data)
    if data ~= nil then
        self.length = #data
        self.data = data
        self.list:RemoveChildrenToPool()
        if self.func ~= nil then
            for i = 1, self.length do
                local cell = self.list:AddItemFromPool()
                self.func(self.classSelf, i, cell, data[i])
            end
        end
    else
        if self.func ~= nil then
            for i = 1, self.length do
                local cell = self.list:GetChildAt(i - 1)
                self.func(self.classSelf, i, cell, self.data[i])
            end
        end
    end
end
return ListManager