//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Arthas_GameEntryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Arthas.GameEntry), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("UpdateProgress", UpdateProgress);
		L.RegFunction("PreLoadComplete", PreLoadComplete);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Sound", get_Sound, set_Sound);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateProgress(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			Arthas.GameEntry.UpdateProgress(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PreLoadComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Arthas.GameEntry.PreLoadComplete();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sound(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Arthas.GameEntry.Sound);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Sound(IntPtr L)
	{
		try
		{
			Arthas.SoundCompoent arg0 = (Arthas.SoundCompoent)ToLua.CheckObject<Arthas.SoundCompoent>(L, 2);
			Arthas.GameEntry.Sound = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

