//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_UIContentScaler_ScreenMatchModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.UIContentScaler.ScreenMatchMode));
		L.RegVar("MatchWidthOrHeight", get_MatchWidthOrHeight, null);
		L.RegVar("MatchWidth", get_MatchWidth, null);
		L.RegVar("MatchHeight", get_MatchHeight, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.UIContentScaler.ScreenMatchMode>.Check = CheckType;
		StackTraits<FairyGUI.UIContentScaler.ScreenMatchMode>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.UIContentScaler.ScreenMatchMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.UIContentScaler.ScreenMatchMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MatchWidthOrHeight(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.UIContentScaler.ScreenMatchMode.MatchWidthOrHeight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MatchWidth(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.UIContentScaler.ScreenMatchMode.MatchWidth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MatchHeight(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.UIContentScaler.ScreenMatchMode.MatchHeight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.UIContentScaler.ScreenMatchMode o = (FairyGUI.UIContentScaler.ScreenMatchMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

