//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_UIObjectFactoryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.UIObjectFactory), typeof(System.Object));
		L.RegFunction("SetPackageItemExtension", SetPackageItemExtension);
		L.RegFunction("SetExtension", SetExtension);
		L.RegFunction("SetLoaderExtension", SetLoaderExtension);
		L.RegFunction("Clear", Clear);
		L.RegFunction("NewObject", NewObject);
		L.RegFunction("New", _CreateFairyGUI_UIObjectFactory);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegFunction("GComponentCreator", FairyGUI_UIObjectFactory_GComponentCreator);
		L.RegFunction("GLoaderCreator", FairyGUI_UIObjectFactory_GLoaderCreator);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_UIObjectFactory(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FairyGUI.UIObjectFactory obj = new FairyGUI.UIObjectFactory();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.UIObjectFactory.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPackageItemExtension(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<System.Type>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				System.Type arg1 = (System.Type)ToLua.ToObject(L, 2);
				FairyGUI.UIObjectFactory.SetPackageItemExtension(arg0, arg1);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<FairyGUI.UIObjectFactory.GComponentCreator>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				FairyGUI.UIObjectFactory.GComponentCreator arg1 = (FairyGUI.UIObjectFactory.GComponentCreator)ToLua.ToObject(L, 2);
				FairyGUI.UIObjectFactory.SetPackageItemExtension(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FairyGUI.UIObjectFactory.SetPackageItemExtension");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetExtension(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			string arg0 = ToLua.CheckString(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 3);
			FairyGUI.UIObjectFactory.SetExtension(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLoaderExtension(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<System.Type>(L, 1))
			{
				System.Type arg0 = (System.Type)ToLua.ToObject(L, 1);
				FairyGUI.UIObjectFactory.SetLoaderExtension(arg0);
				return 0;
			}
			else if (count == 1 && TypeChecker.CheckTypes<FairyGUI.UIObjectFactory.GLoaderCreator>(L, 1))
			{
				FairyGUI.UIObjectFactory.GLoaderCreator arg0 = (FairyGUI.UIObjectFactory.GLoaderCreator)ToLua.ToObject(L, 1);
				FairyGUI.UIObjectFactory.SetLoaderExtension(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FairyGUI.UIObjectFactory.SetLoaderExtension");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FairyGUI.UIObjectFactory.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int NewObject(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<FairyGUI.PackageItem>(L, 1))
			{
				FairyGUI.PackageItem arg0 = (FairyGUI.PackageItem)ToLua.ToObject(L, 1);
				FairyGUI.GObject o = FairyGUI.UIObjectFactory.NewObject(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<FairyGUI.ObjectType>(L, 1))
			{
				FairyGUI.ObjectType arg0 = (FairyGUI.ObjectType)ToLua.ToObject(L, 1);
				FairyGUI.GObject o = FairyGUI.UIObjectFactory.NewObject(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				FairyGUI.PackageItem arg0 = (FairyGUI.PackageItem)ToLua.CheckObject<FairyGUI.PackageItem>(L, 1);
				System.Type arg1 = ToLua.CheckMonoType(L, 2);
				FairyGUI.GObject o = FairyGUI.UIObjectFactory.NewObject(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FairyGUI.UIObjectFactory.NewObject");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIObjectFactory_GComponentCreator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIObjectFactory_GLoaderCreator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

