//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_GoWrapperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.GoWrapper), typeof(FairyGUI.DisplayObject));
		L.RegFunction("SetWrapTarget", SetWrapTarget);
		L.RegFunction("CacheRenderers", CacheRenderers);
		L.RegFunction("Update", Update);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateFairyGUI_GoWrapper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("wrapTarget", get_wrapTarget, set_wrapTarget);
		L.RegVar("renderingOrder", get_renderingOrder, set_renderingOrder);
		L.RegVar("onUpdate", get_onUpdate, set_onUpdate);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_GoWrapper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FairyGUI.GoWrapper obj = new FairyGUI.GoWrapper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
				FairyGUI.GoWrapper obj = new FairyGUI.GoWrapper(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.GoWrapper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetWrapTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)ToLua.CheckObject<FairyGUI.GoWrapper>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.SetWrapTarget(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CacheRenderers(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)ToLua.CheckObject<FairyGUI.GoWrapper>(L, 1);
			obj.CacheRenderers();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)ToLua.CheckObject<FairyGUI.GoWrapper>(L, 1);
			FairyGUI.UpdateContext arg0 = (FairyGUI.UpdateContext)ToLua.CheckObject<FairyGUI.UpdateContext>(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)ToLua.CheckObject<FairyGUI.GoWrapper>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_wrapTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)o;
			UnityEngine.GameObject ret = obj.wrapTarget;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index wrapTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_renderingOrder(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)o;
			int ret = obj.renderingOrder;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index renderingOrder on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onUpdate(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<FairyGUI.UpdateContext>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_wrapTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.wrapTarget = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index wrapTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_renderingOrder(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.renderingOrder = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index renderingOrder on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onUpdate(IntPtr L)
	{
		try
		{
			FairyGUI.GoWrapper obj = (FairyGUI.GoWrapper)ToLua.CheckObject(L, 1, typeof(FairyGUI.GoWrapper));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'FairyGUI.GoWrapper.onUpdate' can only appear on the left hand side of += or -= when used outside of the type 'FairyGUI.GoWrapper'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<FairyGUI.UpdateContext> ev = (System.Action<FairyGUI.UpdateContext>)arg0.func;
				obj.onUpdate += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<FairyGUI.UpdateContext> ev = (System.Action<FairyGUI.UpdateContext>)arg0.func;
				obj.onUpdate -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

