//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_ColorFilterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.ColorFilter), typeof(System.Object));
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("Update", Update);
		L.RegFunction("Invert", Invert);
		L.RegFunction("AdjustSaturation", AdjustSaturation);
		L.RegFunction("AdjustContrast", AdjustContrast);
		L.RegFunction("AdjustBrightness", AdjustBrightness);
		L.RegFunction("AdjustHue", AdjustHue);
		L.RegFunction("Tint", Tint);
		L.RegFunction("Reset", Reset);
		L.RegFunction("ConcatValues", ConcatValues);
		L.RegFunction("New", _CreateFairyGUI_ColorFilter);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("target", get_target, set_target);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_ColorFilter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FairyGUI.ColorFilter obj = new FairyGUI.ColorFilter();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.ColorFilter.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			obj.Update();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			obj.Invert();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AdjustSaturation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.AdjustSaturation(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AdjustContrast(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.AdjustContrast(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AdjustBrightness(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.AdjustBrightness(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AdjustHue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.AdjustHue(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Tint(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
				UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
				obj.Tint(arg0);
				return 0;
			}
			else if (count == 3)
			{
				FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
				UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.Tint(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FairyGUI.ColorFilter.Tint");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			obj.Reset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ConcatValues(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)ToLua.CheckObject<FairyGUI.ColorFilter>(L, 1);
			float[] arg0 = ToLua.CheckParamsNumber<float>(L, 2, count - 1);
			obj.ConcatValues(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)o;
			FairyGUI.DisplayObject ret = obj.target;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FairyGUI.ColorFilter obj = (FairyGUI.ColorFilter)o;
			FairyGUI.DisplayObject arg0 = (FairyGUI.DisplayObject)ToLua.CheckObject<FairyGUI.DisplayObject>(L, 2);
			obj.target = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}
}

