//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_EaseTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.EaseType));
		L.RegVar("Linear", get_Linear, null);
		L.RegVar("SineIn", get_SineIn, null);
		L.RegVar("SineOut", get_SineOut, null);
		L.RegVar("SineInOut", get_SineInOut, null);
		L.RegVar("QuadIn", get_QuadIn, null);
		L.RegVar("QuadOut", get_QuadOut, null);
		L.RegVar("QuadInOut", get_QuadInOut, null);
		L.RegVar("CubicIn", get_CubicIn, null);
		L.RegVar("CubicOut", get_CubicOut, null);
		L.RegVar("CubicInOut", get_CubicInOut, null);
		L.RegVar("QuartIn", get_QuartIn, null);
		L.RegVar("QuartOut", get_QuartOut, null);
		L.RegVar("QuartInOut", get_QuartInOut, null);
		L.RegVar("QuintIn", get_QuintIn, null);
		L.RegVar("QuintOut", get_QuintOut, null);
		L.RegVar("QuintInOut", get_QuintInOut, null);
		L.RegVar("ExpoIn", get_ExpoIn, null);
		L.RegVar("ExpoOut", get_ExpoOut, null);
		L.RegVar("ExpoInOut", get_ExpoInOut, null);
		L.RegVar("CircIn", get_CircIn, null);
		L.RegVar("CircOut", get_CircOut, null);
		L.RegVar("CircInOut", get_CircInOut, null);
		L.RegVar("ElasticIn", get_ElasticIn, null);
		L.RegVar("ElasticOut", get_ElasticOut, null);
		L.RegVar("ElasticInOut", get_ElasticInOut, null);
		L.RegVar("BackIn", get_BackIn, null);
		L.RegVar("BackOut", get_BackOut, null);
		L.RegVar("BackInOut", get_BackInOut, null);
		L.RegVar("BounceIn", get_BounceIn, null);
		L.RegVar("BounceOut", get_BounceOut, null);
		L.RegVar("BounceInOut", get_BounceInOut, null);
		L.RegVar("Custom", get_Custom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.EaseType>.Check = CheckType;
		StackTraits<FairyGUI.EaseType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.EaseType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.EaseType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Linear(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.Linear);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.SineIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.SineOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.SineInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuadIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuadIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuadOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuadOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuadInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuadInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CubicIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CubicIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CubicOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CubicOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CubicInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CubicInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuartIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuartIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuartOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuartOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuartInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuartInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuintIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuintIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuintOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuintOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuintInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.QuintInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ExpoIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ExpoOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ExpoInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CircIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CircIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CircOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CircOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CircInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.CircInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ElasticIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ElasticOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.ElasticInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BackIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BackOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BackInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceIn(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BounceIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BounceOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceInOut(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.BounceInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Custom(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.EaseType.Custom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.EaseType o = (FairyGUI.EaseType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

