//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_FontManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.FontManager), typeof(System.Object));
		L.RegFunction("RegisterFont", RegisterFont);
		L.RegFunction("UnregisterFont", UnregisterFont);
		L.RegFunction("GetFont", GetFont);
		L.RegFunction("Clear", Clear);
		L.RegFunction("New", _CreateFairyGUI_FontManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("sFontFactory", get_sFontFactory, set_sFontFactory);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_FontManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FairyGUI.FontManager obj = new FairyGUI.FontManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.FontManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterFont(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				FairyGUI.BaseFont arg0 = (FairyGUI.BaseFont)ToLua.CheckObject<FairyGUI.BaseFont>(L, 1);
				FairyGUI.FontManager.RegisterFont(arg0);
				return 0;
			}
			else if (count == 2)
			{
				FairyGUI.BaseFont arg0 = (FairyGUI.BaseFont)ToLua.CheckObject<FairyGUI.BaseFont>(L, 1);
				string arg1 = ToLua.CheckString(L, 2);
				FairyGUI.FontManager.RegisterFont(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FairyGUI.FontManager.RegisterFont");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnregisterFont(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.BaseFont arg0 = (FairyGUI.BaseFont)ToLua.CheckObject<FairyGUI.BaseFont>(L, 1);
			FairyGUI.FontManager.UnregisterFont(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFont(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			FairyGUI.BaseFont o = FairyGUI.FontManager.GetFont(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FairyGUI.FontManager.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sFontFactory(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, FairyGUI.FontManager.sFontFactory);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sFontFactory(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<string,FairyGUI.BaseFont> arg0 = (System.Collections.Generic.Dictionary<string,FairyGUI.BaseFont>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,FairyGUI.BaseFont>));
			FairyGUI.FontManager.sFontFactory = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

