//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class libx_BundleAssetRequestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(libx.BundleAssetRequest), typeof(libx.AssetRequest));
		L.RegFunction("New", _Createlibx_BundleAssetRequest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Createlibx_BundleAssetRequest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				libx.BundleAssetRequest obj = new libx.BundleAssetRequest(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: libx.BundleAssetRequest.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

