//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_IO_StreamWriterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.IO.StreamWriter), typeof(System.IO.TextWriter));
		L.RegFunction("Close", Close);
		L.RegFunction("Flush", Flush);
		L.RegFunction("Write", Write);
		L.RegFunction("WriteAsync", WriteAsync);
		L.RegFunction("WriteLineAsync", WriteLineAsync);
		L.RegFunction("FlushAsync", FlushAsync);
		L.RegFunction("New", _CreateSystem_IO_StreamWriter);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Null", get_Null, null);
		L.RegVar("AutoFlush", get_AutoFlush, set_AutoFlush);
		L.RegVar("BaseStream", get_BaseStream, null);
		L.RegVar("Encoding", get_Encoding, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSystem_IO_StreamWriter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<System.IO.Stream>(L, 1))
			{
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 1);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string, bool>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				bool arg1 = LuaDLL.lua_toboolean(L, 2);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.Stream, System.Text.Encoding>(L, 1))
			{
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 1);
				System.Text.Encoding arg1 = (System.Text.Encoding)ToLua.ToObject(L, 2);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<string, bool, System.Text.Encoding>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				bool arg1 = LuaDLL.lua_toboolean(L, 2);
				System.Text.Encoding arg2 = (System.Text.Encoding)ToLua.ToObject(L, 3);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.IO.Stream, System.Text.Encoding, int>(L, 1))
			{
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 1);
				System.Text.Encoding arg1 = (System.Text.Encoding)ToLua.ToObject(L, 2);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 3);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<string, bool, System.Text.Encoding, int>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				bool arg1 = LuaDLL.lua_toboolean(L, 2);
				System.Text.Encoding arg2 = (System.Text.Encoding)ToLua.ToObject(L, 3);
				int arg3 = (int)LuaDLL.lua_tonumber(L, 4);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1, arg2, arg3);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.Stream, System.Text.Encoding, int, bool>(L, 1))
			{
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 1);
				System.Text.Encoding arg1 = (System.Text.Encoding)ToLua.ToObject(L, 2);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 3);
				bool arg3 = LuaDLL.lua_toboolean(L, 4);
				System.IO.StreamWriter obj = new System.IO.StreamWriter(arg0, arg1, arg2, arg3);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: System.IO.StreamWriter.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
			obj.Close();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Flush(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
			obj.Flush();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Write(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, bool>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, double>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				double arg0 = (double)LuaDLL.lua_tonumber(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, long>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				long arg0 = LuaDLL.tolua_toint64(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, ulong>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				ulong arg0 = LuaDLL.tolua_touint64(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, char[]>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, string>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.StreamWriter, object>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.IO.StreamWriter, string, object>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.Write(arg0, arg1);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.StreamWriter, char[], int, int>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				obj.Write(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.StreamWriter, string, object, object>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				obj.Write(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<System.IO.StreamWriter, string, object, object, object>(L, 1))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				object arg3 = ToLua.ToVarObject(L, 5);
				obj.Write(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (TypeChecker.CheckTypes<System.IO.StreamWriter, string>(L, 1) && TypeChecker.CheckParamsType<object>(L, 3, count - 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
				obj.Write(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.StreamWriter.Write");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteAsync(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<char>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char arg0 = (char)LuaDLL.lua_tonumber(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char[]>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.StreamWriter.WriteAsync");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteLineAsync(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				System.Threading.Tasks.Task o = obj.WriteLineAsync();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char arg0 = (char)LuaDLL.lua_tonumber(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char[]>(L, 2))
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.StreamWriter.WriteLineAsync");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FlushAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)ToLua.CheckObject<System.IO.StreamWriter>(L, 1);
			System.Threading.Tasks.Task o = obj.FlushAsync();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Null(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, System.IO.StreamWriter.Null);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AutoFlush(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)o;
			bool ret = obj.AutoFlush;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AutoFlush on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseStream(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)o;
			System.IO.Stream ret = obj.BaseStream;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseStream on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Encoding(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)o;
			System.Text.Encoding ret = obj.Encoding;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Encoding on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AutoFlush(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.StreamWriter obj = (System.IO.StreamWriter)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.AutoFlush = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AutoFlush on a nil value");
		}
	}
}

