//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_IO_TextWriterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.IO.TextWriter), typeof(System.MarshalByRefObject));
		L.RegFunction("Close", Close);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("Flush", Flush);
		L.RegFunction("Synchronized", Synchronized);
		L.RegFunction("Write", Write);
		L.RegFunction("WriteLine", WriteLine);
		L.RegFunction("WriteAsync", WriteAsync);
		L.RegFunction("WriteLineAsync", WriteLineAsync);
		L.RegFunction("FlushAsync", FlushAsync);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Null", get_Null, null);
		L.RegVar("FormatProvider", get_FormatProvider, null);
		L.RegVar("Encoding", get_Encoding, null);
		L.RegVar("NewLine", get_NewLine, set_NewLine);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
			obj.Close();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Flush(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
			obj.Flush();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Synchronized(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextWriter arg0 = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
			System.IO.TextWriter o = System.IO.TextWriter.Synchronized(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Write(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, bool>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, double>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				double arg0 = (double)LuaDLL.lua_tonumber(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, long>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				long arg0 = LuaDLL.tolua_toint64(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, ulong>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				ulong arg0 = LuaDLL.tolua_touint64(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, char[]>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, string>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				obj.Write(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.Write(arg0, arg1);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.TextWriter, char[], int, int>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				obj.Write(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				obj.Write(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object, object, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				object arg3 = ToLua.ToVarObject(L, 5);
				obj.Write(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (TypeChecker.CheckTypes<System.IO.TextWriter, string>(L, 1) && TypeChecker.CheckParamsType<object>(L, 3, count - 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
				obj.Write(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.TextWriter.Write");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteLine(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<System.IO.TextWriter>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				obj.WriteLine();
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, bool>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, double>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				double arg0 = (double)LuaDLL.lua_tonumber(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, long>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				long arg0 = LuaDLL.tolua_toint64(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, ulong>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				ulong arg0 = LuaDLL.tolua_touint64(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, char[]>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, string>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.TextWriter, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				obj.WriteLine(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.WriteLine(arg0, arg1);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.TextWriter, char[], int, int>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				obj.WriteLine(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				obj.WriteLine(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<System.IO.TextWriter, string, object, object, object>(L, 1))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				object arg3 = ToLua.ToVarObject(L, 5);
				obj.WriteLine(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (TypeChecker.CheckTypes<System.IO.TextWriter, string>(L, 1) && TypeChecker.CheckParamsType<object>(L, 3, count - 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
				obj.WriteLine(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.TextWriter.WriteLine");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteAsync(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<char>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char arg0 = (char)LuaDLL.lua_tonumber(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char[]>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				System.Threading.Tasks.Task o = obj.WriteAsync(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.TextWriter.WriteAsync");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteLineAsync(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				System.Threading.Tasks.Task o = obj.WriteLineAsync();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char arg0 = (char)LuaDLL.lua_tonumber(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<char[]>(L, 2))
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
				char[] arg0 = ToLua.CheckCharBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				System.Threading.Tasks.Task o = obj.WriteLineAsync(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.IO.TextWriter.WriteLineAsync");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FlushAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 1);
			System.Threading.Tasks.Task o = obj.FlushAsync();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Null(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, System.IO.TextWriter.Null);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FormatProvider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)o;
			System.IFormatProvider ret = obj.FormatProvider;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FormatProvider on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Encoding(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)o;
			System.Text.Encoding ret = obj.Encoding;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Encoding on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NewLine(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)o;
			string ret = obj.NewLine;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index NewLine on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NewLine(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.IO.TextWriter obj = (System.IO.TextWriter)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.NewLine = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index NewLine on a nil value");
		}
	}
}

